(write(car '(a b c)))
(terpri)
(write(cdr '(a b c)))
(terpri)
(write(car '((a b) c)))
(terpri)
(write(cdr '((a b) (c d) e)))
(terpri)
(write(car (cdr '(a b c d))))
(terpri)
(write-line "*********")

(write(first '(a b c)))
(terpri)
(write(rest '(a b c)))
(terpri)
(write(first '((a b) c)))
(terpri)
(write(rest '((a b) (c d) e)))
(terpri)
(write(first (rest '(a b c d))))
